docs:
  - changed-files:
      - any-glob-to-any-file: '**/docs/**'

config:
  - changed-files:
      - any-glob-to-any-file: '**/config/**'
  - head-branch: ['^config', 'config']

script:
  - changed-files:
      - any-glob-to-any-file: '**/scripts/**'

feature:
  - head-branch: ['^feat', 'feat', '^feature', 'feature']

refactor:
  - head-branch: ['^refactor', 'refactor']

fix:
  - head-branch: ['^fix', 'fix']
