version: '3.1'
services:
  few-mysql:
    container_name: few-mysql8
    image: mysql/mysql-server:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--lower_case_table_names=1", "--max_connections=2048", "--wait_timeout=3600" ]
    ports:
      - "13306:3306"
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d

  few-adminer: # mysql web admin
    container_name: few-adminer
    image: adminer:4
    ports:
      - "18080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=few-mysql8
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=tables-filter tinymce

  few-minio:
    container_name: few-minio
    image: minio/minio
    ports:
        - "9000:9000"
        - "9001:9001"
    shm_size: '1gb'
    environment:
        - MINIO_ACCESS_KEY=thisisroot
        - MINIO_SECRET_KEY=thisisroot
        - MINIO_ROOT_USER=thisisroot
        - MINIO_ROOT_PASSWORD=thisisroot
        - MINIO_REGION_NAME=ap-northeast-2
    command: server /data --console-address ":9001"

  few-mongodb:
    container_name: few-mongodb
    image: mongo
    ports:
        - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
        - MONGO_INITDB_DATABASE=crm
    volumes:
        -   ./mongodb-init.d:/docker-entrypoint-initdb.d:ro
  few-mongo-express:
    container_name: few-mongo-express
    image: mongo-express
    restart: always
    ports:
        - "18081:8081"
    environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=root
        - ME_CONFIG_MONGODB_SERVER=few-mongodb
        - ME_CONFIG_BASICAUTH_USERNAME=root
        - ME_CONFIG_BASICAUTH_PASSWORD=root
