version: '3.1'
services:
    api:
        container_name: api
        image: fewletter/api:latest
        ports:
            - "8080:8080"
        volumes:
            - /var/log/api:/var/log/api
        environment:
            SPRING_PROFILES_ACTIVE: ${API_SPRING_PROFILES_ACTIVE}
            DB_HOSTNAME: ${DB_HOSTNAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            EMAIL_USERNAME: ${EMAIL_USERNAME}
            EMAIL_PASSWORD: ${EMAIL_PASSWORD}
            STORAGE_URL: ${STORAGE_URL}
            STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
            STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
            STORAGE_REGION: ${STORAGE_REGION}
            IMAGE_STORE_BUCKET_NAME: ${IMAGE_STORE_BUCKET_NAME}
            DOCUMENT_STORE_BUCKET_NAME: ${DOCUMENT_STORE_BUCKET_NAME}
            CDN_URL: ${CDN_URL}
            WEBHOOK_DISCORD: ${WEBHOOK_DISCORD}
            TIMEOUT_CONNECT: ${TIMEOUT_CONNECT}
            TIMEOUT_READ: ${TIMEOUT_READ}
