version: '3.1'
services:
    api:
        container_name: api
        image: fewletter/api:latest
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: ${API_SPRING_PROFILES_ACTIVE}
            DB_HOSTNAME: ${DB_HOSTNAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            EMAIL_USERNAME: ${EMAIL_USERNAME}
            EMAIL_PASSWORD: ${EMAIL_PASSWORD}
            IMAGE_STORE_URL: ${IMAGE_STORE_URL}
            IMAGE_STORE_ACCESS_KEY: ${IMAGE_STORE_ACCESS_KEY}
            IMAGE_STORE_SECRET_KEY: ${IMAGE_STORE_SECRET_KEY}
            IMAGE_STORE_BUCKET_NAME: ${IMAGE_STORE_BUCKET_NAME}
            IMAGE_STORE_REGION: ${IMAGE_STORE_REGION}
            CDN_URL: ${CDN_URL}
