spring:
    messages:
        basename:
            ValidationMessages
    profiles:
        group:
            local:
                - security-local
                - client-local
                - api-repo-local
                - email-local
                - storage-local
            prd:
                - security-prd
                - client-prd
                - api-repo-prd
                - email-prd
                - storage-prd

auth:
    batch: ${AUTH_BATCH:0518}

log:
    file:
        path: ${LOGS_ABSOLUTE_PATH:./var/log/api}
