client:
    timeout:
        connect: ${TIMEOUT_CONNECT:5000}
        read: ${TIMEOUT_READ:5000}

webhook:
    discord: ${WEBHOOK_DISCORD}

discord:
    thread-pool:
        core-pool-size: ${DISCORD_THREAD_POOL_CORE_POOL_SIZE:5}
        max-pool-size: ${DISCORD_THREAD_POOL_MAX_POOL_SIZE:15}
        queue-capacity: ${DISCORD_THREAD_POOL_QUEUE_CAPACITY:30}
        wait-for-tasks-to-complete-on-shutdown: ${DISCORD_THREAD_POOL_WAIT_FOR_TASKS_TO_COMPLETE_ON_SHUTDOWN:true}
        await-termination-seconds: ${DISCORD_THREAD_POOL_AWAIT_TERMINATION_SECONDS:60}

database:
    thread-pool:
        core-pool-size: 10
        max-pool-size: 30
        queue-capacity: 70
        wait-for-tasks-to-complete-on-shutdown: true
        await-termination-seconds: 60
