spring:
    messages:
        basename:
            ValidationMessages
    profiles:
        group:
            local:
                - api-repo-local
                - email-local
            prd:
                - api-repo-prd
                - email-prd
