spring:
    profiles:
        group:
            local:
                - api-repo-local
            prd:
                - api-repo-prd
            test:
                - new
                - api-repo-local
