client:
    timeout:
        connect: 5000
        read: 5000

webhook:
    discord: "localhost:8080/webhook/discord/unused"

discord:
    thread-pool:
        core-pool-size: 5
        max-pool-size: 15
        queue-capacity: 30
        wait-for-tasks-to-complete-on-shutdown: true
        await-termination-seconds: 60

database:
    thread-pool:
        core-pool-size: 10
        max-pool-size: 30
        queue-capacity: 70
        wait-for-tasks-to-complete-on-shutdown: true
        await-termination-seconds: 60
