thread-pool:
    database:
        core-pool-size: 10
        max-pool-size: 30
        queue-capacity: 70
        wait-for-tasks-to-complete-on-shutdown: true
        await-termination-seconds: 60
    discord:
        core-pool-size: 5
        max-pool-size: 15
        queue-capacity: 30
        wait-for-tasks-to-complete-on-shutdown: true
        await-termination-seconds: 60
