spring:
    messages:
        basename:
            ValidationMessages
    profiles:
        group:
            local:
                # module
                - security-local
                - web-local
                - email-local
                - storage-local
                - api-repo-local
                # api
                - thread-local
            prd:
                # module
                - security-prd
                - web-prd
                - email-prd
                - storage-prd
                - api-repo-prd
                # api
                - thread-prd
auth:
    batch: ${AUTH_BATCH:0518}

log:
    file:
        path: ${LOGS_ABSOLUTE_PATH:./var/log/api}
