security:
    jwt:
        token:
            validtime:
                access: ${ACCESS_TOKEN_VALIDTIME}
                refresh: ${REFRESH_TOKEN_VALIDTIME}
            secretkey: ${TOKEN_SECRETKEY}
    cors:
        path-patterns: ${CORS_PATH_PATTERNS}
        origin-patterns: ${CORS_ORIGIN_PATTERNS}
        allowed-methods: ${CORS_ALLOWED_METHODS}
        allowed-headers: ${CORS_ALLOWED_HEADERS}
        exposed-headers: ${CORS_EXPOSED_HEADERS}
        allow-credentials: ${CORS_ALLOW_CREDENTIALS}
        max-age: ${CORS_MAX_AGE}
    encryption:
        algorithm: ${ENCRYPTION_ALGORITHM}
        secretKey: ${ENCRYPTION_SECRETKEY}
        transformation: ${ENCRYPTION_TRANSFORMATION}
        keySize: ${ENCRYPTION_KEY_SIZE}
        iv: ${ENCRYPTION_IV}
