spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls:
              enable: true
          EnableSSL:
                enable: true

    provider:
     aws:
      access-key: ${EMAIL_ACCESS_KEY}
      secret-key: ${EMAIL_SECRET_KEY}
      region: ${EMAIL_REGION}
