spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: DevFewFew@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls:
              enable: true
          EnableSSL:
                enable: true
