web:
    security:
        cors:
            path-patterns: "/**"
            origin-patterns: "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
            exposed-headers: "Set-Cookie, Authorization, Content-Type, X-Requested-With, Accept, Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Access-Control-Allow-Origin, Access-Control-Allow-Credentials"
            allow-credentials: true
            max-age: 1800
        jwt:
            token:
                validtime:
                    access: 31557600000
                    refresh: 31557600000
                secretkey: jwtsecretKeyhastolonghowlongidontknow
    client:
        timeout:
            connect: 5000
            read: 5000

webhook:
    discord: "localhost:8080/webhook/discord/unused"
