spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: few.quiz.letter@gmail.com
    password: ${EMAIL_PASSWORD:uace ukqr reoq qfwt}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls:
              enable: true
          EnableSSL:
                enable: true

    provider:
        aws:
            access-key: AKIAQKPILYOIHEPISMF4
            secret-key: 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
            region: ap-northeast-2
