security:
    jwt:
        token:
            validtime:
                access: 31557600000
                refresh: 31557600000
            secretkey: jwtsecretKeyhastolonghowlongidontknow
    encryption:
        algorithm: AES
        secretKey: encryptionsecret
        transformation: AES/CBC/PKCS5Padding
        keySize: 128
        iv: AAAAAAAAAAAAAAAA
