security:
    encryption:
        algorithm: ${ENCRYPTION_ALGORITHM}
        secretKey: ${ENCRYPTION_SECRETKEY}
        transformation: ${ENCRYPTION_TRANSFORMATION}
        keySize: ${ENCRYPTION_KEY_SIZE}
        iv: ${ENCRYPTION_IV}
