storage:
    url: http://127.0.0.1:9000
    access-key: thisisroot
    secret-key: thisisroot
    region: ap-northeast-2

image:
    store:
        bucket-name: picture

cdn:
    url: http://127.0.0.1:9000
