image:
    store:
        url: http://127.0.0.1:9000
        access-key: thisisroot
        secret-key: thisisroot
        bucket-name: picture
        region: ap-northeast-2

cdn:
    url: http://127.0.0.1:9000
