name: 'auto assign label to pull request'

on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/labeler@v5
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          configuration-path: .github/labeler.yml
