name: Validate Test

on:
    pull_request:
        types: [ opened ]
        branches: [ "dev" ]
    workflow_dispatch:

permissions:
    contents: read

env:
    EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

jobs:
    integration-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Cache Gradle
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Jooq Code Generation
              run: |
                  ./gradlew --info jooqCodegenAll

            - name: Test with Gradle
              run: |
                  ./gradlew --info test
