name: WIP
on:
    pull_request:
        types: [ opened, synchronize, reopened, edited ]

jobs:
    wip:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: wip/action@v1.0.0
